name: dp-services

on: [push]

jobs:
  test-py27:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '2.7'
        cache: 'pip'
        cache-dependency-path: |
          **/setup.py
          **/requirements.txt
          **/constraints.txt
    - name: pip-install
      run: make install
    - name: unit-tests
      run: make test
  test-py310:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: |
          **/setup.py
          **/requirements.txt
          **/constraints.txt
    - name: install-cmake
      run: sudo apt-get -y install cmake wget
    - name: install-libssh2
      run: |
        wget https://www.libssh2.org/download/libssh2-1.10.0.tar.gz \
        && tar xf libssh2-1.10.0.tar.gz \
        && cd libssh2-1.10.0/ \
        && mkdir bin \
        && cd bin/ \
        && cmake .. \
        && cmake --build . \
        && sudo make install
    - name: pip-install
      run: make install
    - name: run-tests
      run: make test
